name: "test"

on:
  push:
    branches:
      - "master"

jobs:
  test:
    name: "Tests"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: 'true'

      - name: Setup
        run: npm install --force

      - name: Jest
        run: npm test

      - name: Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          # files: ./coverage1.xml,./coverage2.xml # optional
          directory: ./coverage
          # flags: unittests # optional
          # name: codecov-umbrella # optional
          fail_ci_if_error: true
          # verbose: true # optional (default = false)
